schemaVersion: '2.0.0'

fileExistenceTests:
    - name: 'tor'
      path: '/usr/bin/tor'
      shouldExist: true
      permissions: '-rwxr-xr-x'
    - name: 'tor-resolve'
      path: '/usr/bin/tor-resolve'
      shouldExist: true
      permissions: '-rwxr-xr-x'
    - name: 'tor-gencert'
      path: '/usr/bin/tor-gencert'
      shouldExist: true
      permissions: '-rwxr-xr-x'
    - name: 'torify'
      path: '/usr/bin/torify'
      shouldExist: true
      permissions: '-rwxr-xr-x'
    - name: 'docker-entrypoint.sh'
      path: '/usr/local/bin/docker-entrypoint.sh'
      shouldExist: true
      permissions: '-rwxrwxr-x'
    - name: 'link docker-entrypoint.sh'
      path: '/docker-entrypoint.sh'
      shouldExist: true
      permissions: 'Lrwxrwxrwx'

metadataTest:
    entrypoint: ['docker-entrypoint.sh']
    exposedPorts: ['9050']
    labels:
        - key: 'maintainer'
          value: 'cyclops.zhao@protonmail.com'
